name: Docker Image CI

on:
  push:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.APPSTORE_DOCKER_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: popbalticlsc/cockpit:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
